config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  get 'messages/index'
  get 'messages/create'
  get 'index/create'
  root to: 'users#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :rooms do
    collection do
      get '/:id', to: 'rooms#list_user', as: 'room_list_user'
    end

    resources :messages do
      collection do
        # get 'convention/user/:id', to: 'messages#index', as: 'convention_user'
      end
    end
  end

  get 'rooms/user/:id', to: 'messages#index', as: 'convention_user'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :participants, dependent: :destroy
  has_many :users, through: :participants
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :validatable

  has_many :messages, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :rooms, through: :participants

  scope :all_except, ->(user) { where.not(id: user) }
  scope :get_room_id, -> { rooms.pluck(:id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :null_session

  def index
    user = User.find_by(id: params[:id])
    redirect_to root_path if user.nil?

    list_room_current = current_user.rooms.pluck(:id)
    list_room_user = user.rooms.pluck(:id)
    room_id = list_room_current & list_room_user

    if room_id.first.nil?
      @room = Room.create(name: SecureRandom.hex(6))
      Participant.create([{ user_id: user.id, room_id: @room.id }, { user_id: current_user.id, room_id: @room.id }])
    else
      @room = Room.find_by(id: room_id.first)
    end

    @users = User.all_except(current_user.id)
    @messages = Message.where(room_id: @room.id)
  end

  def create
    @message = Message.new(param_message)

    # Lưu message và gửi broadcast tới room sử dụng background job
    if @message.save
      SendMessageJob.perform_later(params[:message][:room_id], @message)
      render json: { message: 'create success' }, status: 200
    else
      render json: { error: @message.errors.full_messages.first }
    end
  end

  def param_message
    params.require(:message).permit(:room_id, :user_id, :content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def list_user
    @users = Room.find_by(id: params[:id])&.users.all_except(current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    ActionCable.server.disconnect(current_user: current_user)
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all_except(current_user.id)
    # @rooms = current_user.rooms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <a class="navbar-brand" href="/">ActionCable Chat</a>

  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-logout' %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta class="connect-websocket" value="<%= current_user.id if current_user.present? %>">
    <meta id="user-id-login" name="current_user" value="<%= current_user.id if current_user.present? %>">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
  <div>
    <%= render "layouts/header" %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/messages/_detail.html.erb
<% if message.user_id == current_user.id %>
  <div class="container-message mrl-50">
    <p><%= message.content %></p>
    <span class="time-right"><%= message.created_at %></span>
  </div>
<% else %>
  <div class="container-message darker mrr-50">
    <p><%= message.content %></p>
    <span class="time-left"><%= message.created_at %></span>
  </div>
<% end %>

app/views/messages/index.html.erb
<div class="all-content">
  <div class="block-user">
    <%= render partial: "users/list", locals: {users: @users} %>
  </div>

  <div class="block-messages">
    <input type="hidden" class="room-id" value="<%= @room.id %>">
    <input type="hidden" class="current-user-id" value="<%= current_user.id %>">

    <div class="list-message">
      <% if @messages.present? %>
        <% @messages.each do |message| %>
          <%= render partial: 'messages/detail', locals: {message: message}  %>
        <% end %>
      <% else %>
        No message
      <% end %>
    </div>
    <div class="content">
      <%= form_for Message.new, url: room_messages_path(@room.id), scope: :message, method: :post, remote: true, class: 'submit-form' do |form| %>
        <%= form.hidden_field :room_id, value: @room.id %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.text_field :content %>
        <button type="button" class="btn-submit-form btn btn-outline-success">Send message</button>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/_show.html.erb
<p>
  <%= link_to(room.name, room_list_user_rooms_path(room.id), data: {turbo: "false"}) %>
</p>

app/views/rooms/list_user.html.erb
<% @users.each do |user| %>
<!--<p><%#= link_to user.email, convention_user_room_messages_path(params[:id], user.id), data: { turbolinks: false } %></p>-->
<% end %>

app/views/users/_list.html.erb
<div class="list-user d-flex flex-column">
  <% if users.present? %>
    <% users.each do |user| %>
      <%= link_to user.email, convention_user_path(user.id), data: {turbo: "false"}, class: 'btn' %>
    <% end %>
  <% else %>
    No user
  <% end %>
</div>

app/views/users/index.html.erb
<div class="all-content">
  <div class="block-user">
    <%= render partial: "users/list", locals: {users: @users} %>
  </div>
</div>